# Generated by Django 5.2 on 2025-04-14 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(choices=[('Desk', 'Desk'), ('Laptop', 'Laptop'), ('IP Phone', 'IP Phone'), ('Project', 'Project')], max_length=100)),
                ('asset_serial_No', models.CharField(max_length=100, unique=True)),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
                ('asset_issued', models.BooleanField(default=False)),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_location', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('Mezzanine', 'Mezzanine'), ('Second Floor', 'Second Floor'), ('Meeting Room', 'Meeting Room')], max_length=100)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Assetssearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
