# Generated by Django 5.2 on 2025-04-14 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetsissuance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.assets'),
        ),
        migrations.AddField(
            model_name='assetsissuance',
            name='asset_assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
