# Generated by Django 5.2 on 2025-04-15 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0003_notify_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify_manager',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Manager Notification', 'verbose_name_plural': 'Manager Notifications'},
        ),
        migrations.AlterField(
            model_name='notify_manager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notify_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Notification',
                'verbose_name_plural': 'Employee Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
