# Generated by Django 5.2 on 2025-04-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_alter_notify_manager_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify_manager',
            options={},
        ),
        migrations.AddField(
            model_name='notify_manager',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='notify_manager',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_notifications', to='asset_app.assets'),
        ),
    ]
