# Generated by Django 5.2 on 2025-04-16 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0006_notify_manager_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='date_purchased',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 16, 11, 25, 4, 237526, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
