# Generated by Django 5.2 on 2025-04-17 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0007_alter_assets_date_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='date_purchased',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 17, 5, 27, 54, 883449, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_location',
            field=models.CharField(choices=[('Main Room', 'Main Room'), ('Meeting Room', 'Meeting Room')], max_length=100),
        ),
    ]
