# Generated by Django 5.2 on 2025-04-17 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0008_assets_qr_code_alter_assets_date_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='date_purchased',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 17, 7, 39, 50, 641280, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
